#change lib version below when change the build enviroment
ln -s /usr/lib64/libdouble-conversion.so.1 ./ldlib/ibdouble-conversion.so
ln -s /usr/lib64/libSM.so.6  ./ldlib/libSM.so
ln -s /usr/lib64/libICE.so.6 ./ldlib/libICE.so
ln -s /usr/lib64/libXrender.so.1 ./ldlib/libXrender.so
ln -s /usr/lib64/libxcb-render-util.so.0 ./ldlib/libxcb-render-util.so
ln -s /usr/lib64/libxcb-image.so.0 ./ldlib/libxcb-image.so
ln -s /usr/lib64/libxcb-keysyms.so.1 ./ldlib/libxcb-keysyms.so
ln -s /usr/lib64/libxcb-icccm.so.4 ./ldlib/libxcb-icccm.so
ln -s /usr/lib64/libxkbcommon-x11.so.0 ./ldlib/libxkbcommon-x11.so
ln -s /usr/lib64/libjpeg.so.62 ./ldlib/libjpeg.so
ln -s /usr/lib64/libinput.so.10 ./ldlib/libinput.so
ln -s /usr/lib64/libudev.so.1 ./ldlib/libudev.so
ln -s /usr/lib64/libfontconfig.so.1 ./ldlib/libfontconfig.so
ln -s /usr/lib64/libfreetype.so.6 ./ldlib/libfreetype.so
ln -s /usr/lib64/libdbus-1.so.3 ./ldlib/libdbus-1.so
ln -s /usr/lib64/libwayland-server.so.0 ./ldlib/libwayland-server.so
ln -s /usr/lib64/libwayland-client.so.0 ./ldlib/libwayland-client.so
ln -s /usr/lib64/libxkbcommon.so.0 ./ldlib/libxkbcommon.so
ln -s /usr/lib64/libxkbcommon-x11.so.0 ./ldlib/libxkbcommon-x11.so
ln -s /usr/lib64/libwayland-cursor.so.0 ./ldlib/libwayland-cursor.so
ln -s /usr/lib64/libpng16.so.16 ./ldlib/libpng16.so
ln -s /usr/lib64/libharfbuzz-icu.so.0 ./ldlib/libharfbuzz-icu.so
ln -s /usr/lib64/libharfbuzz.so.0 ./ldlib/libharfbuzz.so
ln -s /usr/lib64/libharfbuzz-subset.so.0 ./ldlib/libharfbuzz-subset.so
ln -s /usr/lib64/libz.so.1 ./ldlib/libz.so
ln -s /usr/lib64/libicui18n.so.63 ./ldlib/libicui18n.so
ln -s /usr/lib64/libicuuc.so.63 ./ldlib/libicuuc.so
ln -s /usr/lib64/libicudata.so.63 ./ldlib/libicudata.so
ln -s /usr/lib64/libpcre2-16.so.0 ./ldlib/libpcre2-16.so
ln -s /usr/lib64/libdouble-conversion.so.1 ./ldlib/libdouble-conversion.so
ln -s /usr/lib64/libXi.so.6 ./ldlib/libXi.so
ln -s /usr/lib64/libwayland-egl.so.1 ./ldlib/libwayland-egl.so
